cabal-version:      3.4
name:               calip
version:            0.1.0.0
synopsis:           a CLI tool to deal with networking stuff
-- description:
homepage:           https://github.com/sh-koh/calip
license:            GPL-3.0-or-later
license-file:       LICENSE
author:             sh-koh
maintainer:         70974710+sh-koh@users.noreply.github.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

common exts
    default-extensions: OverloadedStrings
                        NamedFieldPuns
                        RecordWildCards
                        OverloadedRecordDot
                        QuasiQuotes

library
    import:             warnings, exts
    exposed-modules:    Calip
                        Calip.Parser
                        Calip.Types
    -- other-modules:
    build-depends:      base ^>=4.19.2.0
    hs-source-dirs:     src
    default-language:   GHC2021

executable calip
    import:             warnings, exts
    ghc-options:        -O0 -threaded
    main-is:            Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.19.2.0,
        calip

    hs-source-dirs:     exe
    default-language:   GHC2021

test-suite calip-test
    import:             warnings
    default-language:   GHC2021
    -- other-modules:
    -- other-extensions:
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            Main.hs
    build-depends:
        base ^>=4.19.2.0,
        calip
